name: Build Game

on:
  workflow_dispatch:

env:
  GODOT_VERSION: 4.7.2
  GAME_NAME: RipOhChef

jobs:
  build:
    runs-on: ubuntu-24.04

    container:
      image: barichello/godot-ci:4.7.2

    strategy:
      matrix:
        include:
          - platform: windows
            preset: Windows Desktop
            file: RipOhChef.exe

          - platform: mac
            preset: macOS
            file: RipOhChef.zip

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Import Project
        run: godot --headless --import

      - name: Build
        run: |
          mkdir -p build/${{ matrix.platform }}

          godot --headless \
            --export-release "${{ matrix.preset }}" \
            "build/${{ matrix.platform }}/${{ matrix.file }}"

      - name: Upload Build
        uses: actions/upload-artifact@v4
        with:
          name: RipOhChef-${{ matrix.platform }}
          path: build/${{ matrix.platform }}
