name: Build Game

on:
  workflow_dispatch:

env:
  GODOT_VERSION: 4.7.2
  EXPORT_NAME: RipOhChef
  PROJECT_PATH: .

jobs:
  build:
    runs-on: ubuntu-24.04

    container:
      image: barichello/godot-ci:4.7.2

    strategy:
      matrix:
        include:
          - platform: windows
            preset: "Windows Desktop"
            file: "RipOhChef.exe"

          - platform: mac
            preset: "macOS"
            file: "RipOhChef.zip"

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mkdir -v -p ~/.config/
          cp -r /root/.config/godot ~/.config/ || true

          TEMPLATE_DIR=$(find /root/.local/share/godot/export_templates -mindepth 1 -maxdepth 1 -type d | head -1)

          echo "Using templates from: $TEMPLATE_DIR"

          cp -r "$TEMPLATE_DIR" ~/.local/share/godot/export_templates/

      - name: Build
        run: |
          mkdir -v -p build/${{ matrix.platform }}

          EXPORT_DIR="$(readlink -f build)"

          godot --headless --verbose \
            --export-release "${{ matrix.preset }}" \
            "$EXPORT_DIR/${{ matrix.platform }}/${{ matrix.file }}"

      - name: Upload Build
        uses: actions/upload-artifact@v4
        with:
          name: RipOhChef-${{ matrix.platform }}
          path: build/${{ matrix.platform }}